### PR TITLE
Restructure application with React

### PR DESCRIPTION
**Pull request by adhurjaty**
## Summary

Restructures the app into a monorepo form. Applications are in the `./apps` directory
- browser-extension
- webapp

The webapp contains the deno backend in the `api` directory. The root of the webapp directory contains the react frontend. Vite is used to build and paths to `/api` are proxied to the backend.

Currently the homepage shows the react starter template and the `/hello` route demonstrates simple fetching from the backend

I had trouble getting the denoland vscode extension to work with the monorepo format. It appears to be an [open issue](https://github.com/denoland/vscode_deno/issues/878). I included my attempt to get it work with vscode workspace config. My workaround is to open the `api` folder in its own vscode workspace.

This change is largely built from [this tutorial](https://docs.deno.com/runtime/tutorials/how_to_with_npm/react/)

Home page

Screenshot 2024-11-17 at 1 28 58 PM

Hello page

Screenshot 2024-11-17 at 1 29 51 PM

Closes issue #7

### CODE REVIEW

**Review by Melvillian — APPROVED** [review]
This looks good to me. I think there should be a npm script for running the `webapp/api` backend during development mode. Perhaps it should spin up the vite dev server AND the backend Hono server, but that can wait for a future PR.

**Comment by Melvillian** [comment]
@adhurjaty do I understand the CONTRIBUTORS doc correctly in that you should now squash + rebase your commits, push it back up, and then @maxtriano  or I will approve + merge it? Or should I just do squash + merge the pull request (see screenshot below)

image

**Comment by adhurjaty** [comment]
> This looks good to me. I think there should be a npm script for running the `webapp/api` backend during development mode. Perhaps it should spin up the vite dev server AND the backend Hono server, but that can wait for a future PR.

The command to run the stack is `deno task dev` (runs both). I should update the README at some point.

**Comment by adhurjaty** [comment]
> @adhurjaty do I understand the CONTRIBUTORS doc correctly in that you should now squash + rebase your commits, push it back up, and then @maxtriano or I will approve + merge it? Or should I just do squash + merge the pull request (see screenshot below)

I added the preference for rebasing `fixup` commits before squashing and merging (we don't want the fixup commit messages in history).

**Pull request merged**
